name: Build and Release WASM

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Install rust
      run: rustup target add wasm32-unknown-unknown

    - name: Build
      run: |
        cd quillion-wasm
        wasm-pack build --target web --release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: wasm-package
        path: quillion-wasm/pkg/

  create-release:
    runs-on: ubuntu-latest
    needs: build-wasm
    if: github.event_name == 'release'
    
    steps:
    - name: Download
      uses: actions/download-artifact@v4
      with:
        name: wasm-package
        path: wasm-package

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: wasm-package/*
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        body: WASM build for Q
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}